version: '3.7'
services:
  app:
    container_name: descomplica-frontend
    build:
      context: .
      target: ${NODE_ENV}
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
